ROUTERS = {
    "BST_Pueblo_Viejo": 1,
    "BTS_Moron":        2,
    "BTS_Tabuyo":       3,
    "BTS_Blandon":      4,
    "BTS_Iberia":       5,
    "BTS_Calera":       6,
    "BTS_Clavijo":      7,
    "BTS_Cruces":       8,
    "BTS_Irra":         9,
    "BTS_Guamal":       10,
    "BTS_Cabuyal":      11,
}


#TODO: add fiber plans
PLANS = {
    # Inalambrico
    "PLAN FINCA BASICO 2023":               1,
    "PLAN FINCA BASICO 20MBPS 74000":       2,
    "PLAN FINCA BASICO 20MBPS":             3,
    "RESIDENCIAL BASICO 2 (ESPECIAL) 3":    4,
    "RESIDENCIAL BASICO _C16 (ESPECIAL) 2": 5,
    "RESIDENCIAL BASICO _C16 (ESPECIAL) 1": 6,
    "RESIDENCIAL BASICO RURAL 2.3":         7,
    "RESIDENCIAL BASICO RURAL 2.2":         8,
    "RESIDENCIAL BASICO _C16 1":            9,
    "RESIDENCIAL BASICO RURAL 2.1":         10,
    "RESIDENCIAL BASICO 2 (ESPECIAL) 1":    11,
    "RESIDENCIAL BASICO (ESPECIAL) 2":      12,
    "RESIDENCIAL BASICO (ESPECIAL) 1":      13,
    "RESIDENCIAL AVANZADO 2.1":             14,
    "PLAN FINCA BASICO 1":                  15,
    "COMERCIAL BASICO 1":                   16,
    "RESIDENCIAL BASICO _C16 (ESPECIAL)":   17,
    "RESIDENCIAL AVANZADO 2":               18,
    "PLAN FINCA AVANZADO":                  19,
    "RESIDENCIAL BASICO 2(ESPECIAL)":       20,
    "RESIDENCIAL BASICO 10MBPS":            21,
    "RESIDENCIAL BASICO 6":                 22,
    "RESIDENCIAL BASICO 10MBPS 2":          23,
    "RESIDENCIAL BASICO 5":                 24,
    "COMERCIAL BASICO":                     25,
    "RESIDENCIAL BASICO RURAL 2":           26,
    "RESIDENCIAL BASICO 3":                 27,
    "RESIDENCIAL BASICO_RURAL":             28,
    "RESIDENCIAL BASICO 2":                 29,
    "RESIDENCIAL BASICO RURAL 3":           30,
    "RESIDENCIAL BASICO (ESPECIAL)":        31,
    "RESIDENCIAL BASICO":                   32,
    "PLAN FINCA BASICO":                    33,
    "RESIDENCIAL BASICO _C16":              34,
}
